### ISSUE TITLE
data_folder数据集形式问题

### ISSUE THREAD

**Issue by xiaohua-chen** [MediaBrain-SJTU/BCL#1]
您好，感谢您的代码！我想请教一下命令里面data_folder这里的数据集到底是什么形式的呢？您方便把数据集里面的格式展示一下吗？

python train.py BCL_I --bcl --rand_k 1 --lr 0.5 --epochs 2000 --temperature 0.2 --weight_decay 5e-4 --data_folder ${data_folder} --trainSplit cifar100_imbSub_with_subsets/cifar100_split1_D_i.npy  

第二个问题是，您在跑cifar100数据集的时候，在full-shot上的训时间是多长呢？
期待您的回复～

**Comment by Zhihan-Zhou** [comment]
您好，感谢您对我们工作的关注！关于数据集的形式，我们使用的是常用的[cifar100](https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz)数据集；关于训练时间，cifar100 fullshot数据集在3090上1000epoch的运行时间大约是7 hours.
