### ISSUE TITLE
How to calculate the (Many-Medium-Few) results

### ISSUE THREAD

**Issue by junkangwu** [MediaBrain-SJTU/BCL#3]

**Comment by Zhihan-Zhou** [comment]
Hi,  Junkang!

Thanks for your interest in our work. You can evaluate the perclass acc [here](https://github.com/MediaBrain-SJTU/BCL/blob/main/eval_cifar.py#L47) and print the disjoint summary [here](https://github.com/MediaBrain-SJTU/BCL/blob/main/utils.py#L66). Please let me know if you have any further questions.

**Comment by junkangwu** [comment]
Oh, thank you for your response.
